    "XQWatcherServerAsGroup":{
      "Type":"AWS::AutoScaling::AutoScalingGroup",
      "Properties":{
        "AvailabilityZones":[
          {
            "Fn::GetAtt":[
              "XQWatcherSubnet01",
              "AvailabilityZone"
            ]
          },
          {
            "Fn::GetAtt":[
              "XQWatcherSubnet02",
              "AvailabilityZone"
            ]
          }
        ],
        "VPCZoneIdentifier":[
          {
            "Ref":"XQWatcherSubnet01"
          },
          {
            "Ref":"XQWatcherSubnet02"
          }
        ],
        "Tags":[
          {
            "Key":"Name",
            "Value": {"Fn::Join": ["-",[{"Ref": "EnvironmentTag"},{"Ref": "DeploymentTag"},"xqwatcher"]]},
            "PropagateAtLaunch":true
          },
          {
            "Key":"play",
            "Value":"xqwatcher",
            "PropagateAtLaunch":true
          },
          {
            "Key":"services",
            "Value":"xqwatcher",
            "PropagateAtLaunch":true
          },
          {
            "Key":"environment",
            "Value":{
              "Ref":"EnvironmentTag"
            },
            "PropagateAtLaunch":true
          },
          {
            "Key":"deployment",
            "Value":{
              "Ref":"DeploymentTag"
            },
            "PropagateAtLaunch":true
          }
        ],
        "LaunchConfigurationName":{
          "Ref":"XQWatcherServer"
        },
        "MinSize":{
          "Ref":"XQWatcherDesiredCapacity"
        },
        "MaxSize":{
          "Ref":"XQWatcherDesiredCapacity"
        },
        "DesiredCapacity":{
          "Ref":"XQWatcherDesiredCapacity"
        }
    }
