Vagrant.require_version ">= 1.8.7"
unless Vagrant.has_plugin?("vagrant-vbguest")
  raise "Please install the vagrant-vbguest plugin by running `vagrant plugin install vagrant-vbguest`"
end

VAGRANTFILE_API_VERSION = "2"

# Analyticstack requires more memory than Devstack.
MEMORY = 6144
CPU_COUNT = 2

vm_guest_ip = "192.168.33.10"
if ENV["VAGRANT_GUEST_IP"]
  vm_guest_ip = ENV["VAGRANT_GUEST_IP"]
end

# These are versioning variables in the roles. Each can be overridden, first
# with OPENEDX_RELEASE, and then with a specific environment variable of the
# same name but upper-cased.
VERSION_VARS = [
  'EDX_PLATFORM_VERSION',
  'CONFIGURATION_VERSION',
  'CERTS_VERSION',
  'FORUM_VERSION',
  'XQUEUE_VERSION',
  'DEMO_VERSION',
  'ECOMMERCE_VERSION',
  'ECOMMERCE_WORKER_VERSION',
  'ANALYTICS_API_VERSION',
  'INSIGHTS_VERSION',
]

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Creates a devstack from a base Ubuntu 16.04 image for virtualbox
  config.vm.box = "bento/ubuntu-16.04"

  config.vm.network :private_network, ip: vm_guest_ip

  # If you want to run the box but don't need network ports, set VAGRANT_NO_PORTS=1.
  # This is useful if you want to run more than one box at once.
  if not ENV['VAGRANT_NO_PORTS']
    config.vm.network :forwarded_port, guest: 8000, host: 8000  # LMS
    config.vm.network :forwarded_port, guest: 8001, host: 8001  # Studio
    config.vm.network :forwarded_port, guest: 8002, host: 8002  # Ecommerce
    config.vm.network :forwarded_port, guest: 8003, host: 8003  # LMS for Bok Choy
    config.vm.network :forwarded_port, guest: 8031, host: 8031  # Studio for Bok Choy
    config.vm.network :forwarded_port, guest: 8120, host: 8120  # edX Notes Service
    config.vm.network :forwarded_port, guest: 8765, host: 8765
    config.vm.network :forwarded_port, guest: 9200, host: 9200
    config.vm.network :forwarded_port, guest: 18080, host: 18080
    config.vm.network :forwarded_port, guest: 8100, host: 8100  # Analytics Data API
    config.vm.network :forwarded_port, guest: 8110, host: 8110  # Insights
    config.vm.network :forwarded_port, guest: 50070, host: 50070  # HDFS Admin UI
    config.vm.network :forwarded_port, guest: 8088, host: 8088  # Hadoop Resource Manager
  end

  config.ssh.insert_key = true

 # Enable X11 forwarding so we can interact with GUI applications
  if ENV['VAGRANT_X11']
    config.ssh.forward_x11 = true
  end

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", MEMORY.to_s]
    vb.customize ["modifyvm", :id, "--cpus", CPU_COUNT.to_s]
  end


  # Make LC_ALL default to en_US.UTF-8 instead of en_US.
  # See: https://github.com/mitchellh/vagrant/issues/1188
  config.vm.provision "shell", inline: 'echo \'LC_ALL="en_US.UTF-8"\' > /etc/default/locale'

  # Get ready for ansible on this box.
  config.vm.provision "shell", path: '../../../util/install/ansible-bootstrap.sh'

  # Use vagrant-vbguest plugin to make sure Guest Additions are in sync
  config.vbguest.auto_reboot = true
  config.vbguest.auto_update = true

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "../../../playbooks/vagrant-analytics.yml"
    ansible.verbose = "vvvv"

    ansible.extra_vars = {}
    VERSION_VARS.each do |var|
      if ENV['OPENEDX_RELEASE']
        ansible.extra_vars[var] = ENV['OPENEDX_RELEASE']
      end
      env_var = var.upcase
      if ENV[env_var]
        ansible.extra_vars[var] = ENV[env_var]
      end
    end

  end
end
