# -*- mode: ruby -*-
# vi: set ft=ruby :

MEMORY = 2048
CPU_COUNT = 2

Vagrant.configure("2") do |config|
  config.vm.box     = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.network :private_network, ip: "192.168.33.10"
  config.vm.hostname = "vagrant"
  config.ssh.forward_agent = true

  #nfs_setting = RUBY_PLATFORM =~ /darwin/ || RUBY_PLATFORM =~ /linux/
  #config.vm.synced_folder "edx-platform", "/opt/wwc/edx-platform", id: "vagrant-root", :nfs => nfs_setting, :create => true, owner: "www-data", group: "www-data"
  config.vm.synced_folder "edx-platform", "/opt/wwc/edx-platform", id: "vagrant-root", :create => true, owner: "www-data", group: "www-data"

  # Configure /etc/hosts on the host machine
  # This requires the vagrant-hostsupdater plugin
  # To install:
  #     vagrant plugin install vagrant-hostsupdater
  config.hostsupdater.aliases = ["preview.localhost"]

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", MEMORY.to_s]

    # You can adjust this to the amount of CPUs your system has available
    vb.customize ["modifyvm", :id, "--cpus", CPU_COUNT.to_s]

    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.provision :ansible do |ansible|
    # point Vagrant at the location of your playbook you want to run
    ansible.playbook = "../../playbooks/vagrant-devstack-gui.yml"
    ansible.inventory_path = "../../playbooks/vagrant/inventory.ini"
    ansible.extra_vars = { EDXAPP_DEV_MODE: true }
    ansible.verbose = "extra"
    ansible.sudo = true
    ansible.sudo_user = "root"
  end
end
