# Vagrantfile for testing throwaway Ansible playbooks. To use, create a playbook
# under /playbooks (e.g., "foo.yml"), export its name (e.g., "foo") as the value
# of the environment variable VAGRANT_ANSIBLE_PLAYBOOK, and execute `vagrant up`
# from within this directory.
MEMORY = 1024
CPU_COUNT = 2

Vagrant.configure("2") do |config|

  config.vm.box     = "ubuntu_xenial"

  config.vm.network :private_network, ip: "192.168.33.20"
  config.vm.network :forwarded_port, guest: 8555, host: 8555

  config.ssh.insert_key = true

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", MEMORY.to_s]

    # You can adjust this to the amount of CPUs your system has available
    vb.customize ["modifyvm", :id, "--cpus", CPU_COUNT.to_s]
    vb.customize ['modifyvm', :id, '--nictype1', 'virtio']
  end

  config.ssh.forward_x11 = true

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "../../../playbooks/" + ENV['VAGRANT_ANSIBLE_PLAYBOOK'] + ".yml"
    ansible.verbose = "vvvv"
    ansible.extra_vars = {
        edx_django_service_version: 'ammar/changes-for-config'
    }
  end
end
