#! /usr/bin/env python

import json
import click
import yaml
import sys

@click.command()
@click.argument('files', nargs=-1, type=click.Path())
def join_json(files):
    """ This script merges multiple JSON documents into a single namespace, then dumps as YAML """
    data = dict()
    for file in files:
        click.echo('# ingested %s' % file)
        with open(file) as filehandle:
            data.update(json.load(filehandle))
    print yaml.safe_dump(data)

if __name__ == '__main__':
    join_json()
