set nocompatible

" Turn on syntax highlighting
syntax on

" Handle filetypes 
filetype on

" Handle filetype-based plugins and indentation rules
filetype plugin indent on

" Highlight matching delimiters (brackets, braces, quotes, etc.)
set showmatch

" Show the following replacement characters on :set list
set listchars=tab:→\ ,trail:·,nbsp:¤,precedes:«,extends:»,eol:↲

" Never autocomplete filenames that match the following
set wildignore+=*.pyc,*.pyo

" Silence error bells
set noerrorbells visualbell

" Standard indentation rules:

" - A tab character is 8 spaces wide
set tabstop=8
" - a block indents four spaces
set shiftwidth=4
" - Pressing the tab key indents by four spaces
set softtabstop=4
" - Always render indentation as spaces
set expandtab
