#!/bin/bash

mysql --host="{{ mysql_login_host }}" \
    --port="{{ mysql_login_port }}" \
    --user="{{ mysql_login_user }}" \
    -p \
    --ssl-ca="{{ mysql_ca_cert_path }}" \
    --ssl-cert="{{ mysql_client_cert_path }}" \
    --ssl-key="{{ mysql_client_key_path }}" \
    "$@"
