//send job metadata and junit reports with page size set to 50 (each event contains max 50 test cases)
splunkins.sendTestReport(50)


// Send paver timing logs to Splunk
splunkins.archive("**/timing*.log", null, false, "10MB")

// Index the codecov metrics generated by gather-codecov-metrics
splunkins.archive("**/codecov_metrics.json", null, false, "1MB")
